# Generated by Django 5.0.6 on 2024-06-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_remove_chatsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
